[2023-12-05 15:34:39,922] {scheduler_job.py:181} INFO - Started process (PID=166) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:34:39,924] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:34:39,926] {logging_mixin.py:104} INFO - [2023-12-05 15:34:39,926] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:34:39,943] {logging_mixin.py:104} INFO - [2023-12-05 15:34:39,940] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:34:39,945] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:34:39,962] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.044 seconds
[2023-12-05 15:35:10,477] {scheduler_job.py:181} INFO - Started process (PID=175) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:35:10,480] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:35:10,482] {logging_mixin.py:104} INFO - [2023-12-05 15:35:10,482] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:35:10,503] {logging_mixin.py:104} INFO - [2023-12-05 15:35:10,499] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:35:10,505] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:35:10,524] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.053 seconds
[2023-12-05 15:35:41,159] {scheduler_job.py:181} INFO - Started process (PID=201) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:35:41,161] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:35:41,163] {logging_mixin.py:104} INFO - [2023-12-05 15:35:41,163] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:35:41,180] {logging_mixin.py:104} INFO - [2023-12-05 15:35:41,176] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:35:41,182] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:35:41,205] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.050 seconds
[2023-12-05 15:36:11,452] {scheduler_job.py:181} INFO - Started process (PID=227) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:36:11,455] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:36:11,457] {logging_mixin.py:104} INFO - [2023-12-05 15:36:11,457] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:36:11,486] {logging_mixin.py:104} INFO - [2023-12-05 15:36:11,482] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:36:11,489] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:36:11,510] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.064 seconds
[2023-12-05 15:36:41,685] {scheduler_job.py:181} INFO - Started process (PID=229) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:36:41,688] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:36:41,690] {logging_mixin.py:104} INFO - [2023-12-05 15:36:41,689] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:36:41,712] {logging_mixin.py:104} INFO - [2023-12-05 15:36:41,709] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:36:41,713] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:36:41,729] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.051 seconds
[2023-12-05 15:37:11,931] {scheduler_job.py:181} INFO - Started process (PID=231) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:37:11,934] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:37:11,935] {logging_mixin.py:104} INFO - [2023-12-05 15:37:11,935] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:37:11,960] {logging_mixin.py:104} INFO - [2023-12-05 15:37:11,956] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:37:11,962] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:37:11,984] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.057 seconds
[2023-12-05 15:37:42,161] {scheduler_job.py:181} INFO - Started process (PID=233) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:37:42,164] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:37:42,166] {logging_mixin.py:104} INFO - [2023-12-05 15:37:42,165] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:37:42,189] {logging_mixin.py:104} INFO - [2023-12-05 15:37:42,186] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:37:42,191] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:37:42,211] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 15:38:12,393] {scheduler_job.py:181} INFO - Started process (PID=235) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:38:12,401] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:38:12,404] {logging_mixin.py:104} INFO - [2023-12-05 15:38:12,403] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:38:12,427] {logging_mixin.py:104} INFO - [2023-12-05 15:38:12,423] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:38:12,429] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:38:12,451] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.064 seconds
[2023-12-05 15:38:42,609] {scheduler_job.py:181} INFO - Started process (PID=237) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:38:42,612] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:38:42,613] {logging_mixin.py:104} INFO - [2023-12-05 15:38:42,613] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:38:42,635] {logging_mixin.py:104} INFO - [2023-12-05 15:38:42,631] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:38:42,637] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:38:42,659] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 15:39:12,841] {scheduler_job.py:181} INFO - Started process (PID=239) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:39:12,845] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:39:12,847] {logging_mixin.py:104} INFO - [2023-12-05 15:39:12,846] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:39:12,870] {logging_mixin.py:104} INFO - [2023-12-05 15:39:12,867] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:39:12,872] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:39:12,894] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.059 seconds
[2023-12-05 15:39:43,318] {scheduler_job.py:181} INFO - Started process (PID=241) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:39:43,322] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:39:43,324] {logging_mixin.py:104} INFO - [2023-12-05 15:39:43,324] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:39:43,347] {logging_mixin.py:104} INFO - [2023-12-05 15:39:43,344] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:39:43,349] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:39:43,366] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 15:40:14,096] {scheduler_job.py:181} INFO - Started process (PID=243) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:40:14,099] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:40:14,101] {logging_mixin.py:104} INFO - [2023-12-05 15:40:14,100] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:40:14,124] {logging_mixin.py:104} INFO - [2023-12-05 15:40:14,119] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:40:14,126] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:40:14,147] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 15:40:44,841] {scheduler_job.py:181} INFO - Started process (PID=245) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:40:44,844] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:40:44,846] {logging_mixin.py:104} INFO - [2023-12-05 15:40:44,846] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:40:44,867] {logging_mixin.py:104} INFO - [2023-12-05 15:40:44,863] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:40:44,869] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:40:44,890] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 15:41:15,649] {scheduler_job.py:181} INFO - Started process (PID=247) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:41:15,652] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:41:15,654] {logging_mixin.py:104} INFO - [2023-12-05 15:41:15,654] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:41:15,678] {logging_mixin.py:104} INFO - [2023-12-05 15:41:15,674] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:41:15,680] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:41:15,704] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.060 seconds
[2023-12-05 15:41:46,387] {scheduler_job.py:181} INFO - Started process (PID=249) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:41:46,390] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:41:46,392] {logging_mixin.py:104} INFO - [2023-12-05 15:41:46,392] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:41:46,413] {logging_mixin.py:104} INFO - [2023-12-05 15:41:46,408] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:41:46,415] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:41:46,439] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.057 seconds
[2023-12-05 15:42:17,156] {scheduler_job.py:181} INFO - Started process (PID=251) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:42:17,159] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:42:17,161] {logging_mixin.py:104} INFO - [2023-12-05 15:42:17,161] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:42:17,182] {logging_mixin.py:104} INFO - [2023-12-05 15:42:17,178] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:42:17,184] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:42:17,205] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.054 seconds
[2023-12-05 15:45:13,244] {scheduler_job.py:181} INFO - Started process (PID=167) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:45:13,246] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:45:13,248] {logging_mixin.py:104} INFO - [2023-12-05 15:45:13,248] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:45:13,266] {logging_mixin.py:104} INFO - [2023-12-05 15:45:13,262] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:45:13,268] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:45:13,286] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.045 seconds
[2023-12-05 15:45:43,761] {scheduler_job.py:181} INFO - Started process (PID=169) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:45:43,765] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:45:43,766] {logging_mixin.py:104} INFO - [2023-12-05 15:45:43,766] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:45:43,783] {logging_mixin.py:104} INFO - [2023-12-05 15:45:43,780] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:45:43,784] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:45:43,799] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.043 seconds
[2023-12-05 15:46:14,512] {scheduler_job.py:181} INFO - Started process (PID=190) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:46:14,515] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:46:14,516] {logging_mixin.py:104} INFO - [2023-12-05 15:46:14,516] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:46:14,533] {logging_mixin.py:104} INFO - [2023-12-05 15:46:14,530] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:46:14,535] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:46:14,556] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.048 seconds
[2023-12-05 15:46:44,651] {scheduler_job.py:181} INFO - Started process (PID=227) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:46:44,653] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:46:44,655] {logging_mixin.py:104} INFO - [2023-12-05 15:46:44,655] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:46:44,676] {logging_mixin.py:104} INFO - [2023-12-05 15:46:44,672] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:46:44,678] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:46:44,697] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.050 seconds
[2023-12-05 15:47:14,839] {scheduler_job.py:181} INFO - Started process (PID=230) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:47:14,842] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:47:14,844] {logging_mixin.py:104} INFO - [2023-12-05 15:47:14,843] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:47:14,865] {logging_mixin.py:104} INFO - [2023-12-05 15:47:14,862] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:47:14,867] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:47:14,885] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.051 seconds
[2023-12-05 15:47:45,048] {scheduler_job.py:181} INFO - Started process (PID=232) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:47:45,052] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:47:45,054] {logging_mixin.py:104} INFO - [2023-12-05 15:47:45,054] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:47:45,080] {logging_mixin.py:104} INFO - [2023-12-05 15:47:45,076] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:47:45,081] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:47:45,099] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.058 seconds
[2023-12-05 15:48:15,284] {scheduler_job.py:181} INFO - Started process (PID=234) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:48:15,286] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:48:15,288] {logging_mixin.py:104} INFO - [2023-12-05 15:48:15,288] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:48:15,315] {logging_mixin.py:104} INFO - [2023-12-05 15:48:15,310] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:48:15,317] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:48:15,338] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.059 seconds
[2023-12-05 15:48:45,490] {scheduler_job.py:181} INFO - Started process (PID=236) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:48:45,499] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:48:45,501] {logging_mixin.py:104} INFO - [2023-12-05 15:48:45,501] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:48:45,525] {logging_mixin.py:104} INFO - [2023-12-05 15:48:45,520] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:48:45,528] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:48:45,549] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.065 seconds
[2023-12-05 15:49:15,735] {scheduler_job.py:181} INFO - Started process (PID=238) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:49:15,738] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:49:15,739] {logging_mixin.py:104} INFO - [2023-12-05 15:49:15,739] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:49:15,759] {logging_mixin.py:104} INFO - [2023-12-05 15:49:15,755] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:49:15,761] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:49:15,782] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.052 seconds
[2023-12-05 15:49:45,936] {scheduler_job.py:181} INFO - Started process (PID=240) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:49:45,940] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:49:45,941] {logging_mixin.py:104} INFO - [2023-12-05 15:49:45,941] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:49:45,964] {logging_mixin.py:104} INFO - [2023-12-05 15:49:45,960] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:49:45,966] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:49:45,986] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 15:50:16,490] {scheduler_job.py:181} INFO - Started process (PID=242) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:50:16,493] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:50:16,496] {logging_mixin.py:104} INFO - [2023-12-05 15:50:16,495] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:50:16,522] {logging_mixin.py:104} INFO - [2023-12-05 15:50:16,517] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:50:16,524] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:50:16,545] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 15:50:47,252] {scheduler_job.py:181} INFO - Started process (PID=244) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:50:47,255] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:50:47,257] {logging_mixin.py:104} INFO - [2023-12-05 15:50:47,257] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:50:47,279] {logging_mixin.py:104} INFO - [2023-12-05 15:50:47,275] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:50:47,281] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:50:47,303] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 15:51:18,022] {scheduler_job.py:181} INFO - Started process (PID=246) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:51:18,026] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:51:18,027] {logging_mixin.py:104} INFO - [2023-12-05 15:51:18,027] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:51:18,052] {logging_mixin.py:104} INFO - [2023-12-05 15:51:18,047] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:51:18,054] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:51:18,076] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.059 seconds
[2023-12-05 15:51:48,804] {scheduler_job.py:181} INFO - Started process (PID=248) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:51:48,807] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:51:48,809] {logging_mixin.py:104} INFO - [2023-12-05 15:51:48,808] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:51:48,828] {logging_mixin.py:104} INFO - [2023-12-05 15:51:48,824] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:51:48,830] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:51:48,852] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.053 seconds
[2023-12-05 15:52:19,531] {scheduler_job.py:181} INFO - Started process (PID=250) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:52:19,534] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:52:19,536] {logging_mixin.py:104} INFO - [2023-12-05 15:52:19,535] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:52:19,555] {logging_mixin.py:104} INFO - [2023-12-05 15:52:19,551] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:52:19,557] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:52:19,578] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.052 seconds
[2023-12-05 15:52:50,297] {scheduler_job.py:181} INFO - Started process (PID=252) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:52:50,300] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:52:50,302] {logging_mixin.py:104} INFO - [2023-12-05 15:52:50,301] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:52:50,326] {logging_mixin.py:104} INFO - [2023-12-05 15:52:50,322] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:52:50,329] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:52:50,350] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.059 seconds
[2023-12-05 15:53:21,053] {scheduler_job.py:181} INFO - Started process (PID=254) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:53:21,055] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:53:21,057] {logging_mixin.py:104} INFO - [2023-12-05 15:53:21,057] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:53:21,080] {logging_mixin.py:104} INFO - [2023-12-05 15:53:21,076] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:53:21,083] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:53:21,105] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.058 seconds
[2023-12-05 15:53:51,830] {scheduler_job.py:181} INFO - Started process (PID=256) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:53:51,833] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:53:51,835] {logging_mixin.py:104} INFO - [2023-12-05 15:53:51,834] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:53:51,857] {logging_mixin.py:104} INFO - [2023-12-05 15:53:51,852] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:53:51,859] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:53:51,881] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.057 seconds
[2023-12-05 15:54:22,565] {scheduler_job.py:181} INFO - Started process (PID=258) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:54:22,568] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:54:22,570] {logging_mixin.py:104} INFO - [2023-12-05 15:54:22,570] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:54:22,591] {logging_mixin.py:104} INFO - [2023-12-05 15:54:22,587] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:54:22,593] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:54:22,613] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.054 seconds
[2023-12-05 15:54:53,233] {scheduler_job.py:181} INFO - Started process (PID=260) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:54:53,236] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:54:53,237] {logging_mixin.py:104} INFO - [2023-12-05 15:54:53,237] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:54:53,262] {logging_mixin.py:104} INFO - [2023-12-05 15:54:53,258] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:54:53,265] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:54:53,289] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 15:55:23,993] {scheduler_job.py:181} INFO - Started process (PID=262) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:55:23,997] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:55:23,999] {logging_mixin.py:104} INFO - [2023-12-05 15:55:23,999] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:55:24,022] {logging_mixin.py:104} INFO - [2023-12-05 15:55:24,018] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:55:24,024] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:55:24,047] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.060 seconds
[2023-12-05 15:55:54,769] {scheduler_job.py:181} INFO - Started process (PID=264) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:55:54,772] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:55:54,774] {logging_mixin.py:104} INFO - [2023-12-05 15:55:54,774] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:55:54,796] {logging_mixin.py:104} INFO - [2023-12-05 15:55:54,792] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:55:54,798] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:55:54,818] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 15:56:25,531] {scheduler_job.py:181} INFO - Started process (PID=266) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:56:25,534] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:56:25,535] {logging_mixin.py:104} INFO - [2023-12-05 15:56:25,535] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:56:25,557] {logging_mixin.py:104} INFO - [2023-12-05 15:56:25,553] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:56:25,559] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:56:25,581] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 15:56:56,314] {scheduler_job.py:181} INFO - Started process (PID=268) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:56:56,316] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:56:56,318] {logging_mixin.py:104} INFO - [2023-12-05 15:56:56,318] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:56:56,342] {logging_mixin.py:104} INFO - [2023-12-05 15:56:56,338] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:56:56,344] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:56:56,365] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 15:57:27,102] {scheduler_job.py:181} INFO - Started process (PID=270) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:57:27,104] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:57:27,106] {logging_mixin.py:104} INFO - [2023-12-05 15:57:27,106] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:57:27,126] {logging_mixin.py:104} INFO - [2023-12-05 15:57:27,123] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:57:27,128] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:57:27,148] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.052 seconds
[2023-12-05 15:57:57,867] {scheduler_job.py:181} INFO - Started process (PID=272) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:57:57,870] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:57:57,872] {logging_mixin.py:104} INFO - [2023-12-05 15:57:57,871] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:57:57,891] {logging_mixin.py:104} INFO - [2023-12-05 15:57:57,887] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:57:57,893] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:57:57,916] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.054 seconds
[2023-12-05 15:58:28,651] {scheduler_job.py:181} INFO - Started process (PID=274) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:58:28,654] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:58:28,659] {logging_mixin.py:104} INFO - [2023-12-05 15:58:28,658] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:58:28,679] {logging_mixin.py:104} INFO - [2023-12-05 15:58:28,676] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:58:28,681] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:58:28,700] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 15:58:59,394] {scheduler_job.py:181} INFO - Started process (PID=276) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:58:59,398] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:58:59,400] {logging_mixin.py:104} INFO - [2023-12-05 15:58:59,399] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:58:59,419] {logging_mixin.py:104} INFO - [2023-12-05 15:58:59,416] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:58:59,421] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:58:59,442] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 15:59:30,182] {scheduler_job.py:181} INFO - Started process (PID=278) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 15:59:30,185] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 15:59:30,186] {logging_mixin.py:104} INFO - [2023-12-05 15:59:30,186] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 15:59:30,206] {logging_mixin.py:104} INFO - [2023-12-05 15:59:30,202] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 15:59:30,207] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 15:59:30,227] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.050 seconds
[2023-12-05 16:00:00,732] {scheduler_job.py:181} INFO - Started process (PID=280) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:00:00,735] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:00:00,737] {logging_mixin.py:104} INFO - [2023-12-05 16:00:00,736] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:00:00,755] {logging_mixin.py:104} INFO - [2023-12-05 16:00:00,752] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:00:00,757] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:00:00,777] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.049 seconds
[2023-12-05 16:00:31,365] {scheduler_job.py:181} INFO - Started process (PID=282) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:00:31,368] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:00:31,370] {logging_mixin.py:104} INFO - [2023-12-05 16:00:31,370] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:00:31,387] {logging_mixin.py:104} INFO - [2023-12-05 16:00:31,384] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:00:31,388] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:00:31,406] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.046 seconds
[2023-12-05 16:04:05,329] {scheduler_job.py:181} INFO - Started process (PID=99) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:04:05,331] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:04:05,332] {logging_mixin.py:104} INFO - [2023-12-05 16:04:05,332] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:04:05,347] {logging_mixin.py:104} INFO - [2023-12-05 16:04:05,345] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:04:05,349] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:04:05,365] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.040 seconds
[2023-12-05 16:05:40,056] {scheduler_job.py:181} INFO - Started process (PID=99) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:05:40,058] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:05:40,059] {logging_mixin.py:104} INFO - [2023-12-05 16:05:40,059] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:05:40,075] {logging_mixin.py:104} INFO - [2023-12-05 16:05:40,072] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:05:40,076] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:05:40,093] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.041 seconds
[2023-12-05 16:12:13,525] {scheduler_job.py:181} INFO - Started process (PID=167) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:12:13,527] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:12:13,528] {logging_mixin.py:104} INFO - [2023-12-05 16:12:13,528] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:12:13,545] {logging_mixin.py:104} INFO - [2023-12-05 16:12:13,542] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:12:13,546] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:12:13,565] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.044 seconds
[2023-12-05 16:12:44,104] {scheduler_job.py:181} INFO - Started process (PID=169) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:12:44,107] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:12:44,109] {logging_mixin.py:104} INFO - [2023-12-05 16:12:44,108] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:12:44,132] {logging_mixin.py:104} INFO - [2023-12-05 16:12:44,128] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:12:44,134] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:12:44,153] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.054 seconds
[2023-12-05 16:13:14,837] {scheduler_job.py:181} INFO - Started process (PID=171) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:13:14,842] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:13:14,844] {logging_mixin.py:104} INFO - [2023-12-05 16:13:14,844] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:13:14,876] {logging_mixin.py:104} INFO - [2023-12-05 16:13:14,870] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:13:14,878] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:13:14,911] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.080 seconds
[2023-12-05 16:13:45,095] {scheduler_job.py:181} INFO - Started process (PID=173) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:13:45,097] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:13:45,099] {logging_mixin.py:104} INFO - [2023-12-05 16:13:45,099] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:13:45,128] {logging_mixin.py:104} INFO - [2023-12-05 16:13:45,123] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:13:45,130] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:13:45,152] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.063 seconds
[2023-12-05 16:14:15,327] {scheduler_job.py:181} INFO - Started process (PID=175) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:14:15,331] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:14:15,333] {logging_mixin.py:104} INFO - [2023-12-05 16:14:15,332] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:14:15,361] {logging_mixin.py:104} INFO - [2023-12-05 16:14:15,356] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:14:15,363] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:14:15,384] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.063 seconds
[2023-12-05 16:14:45,531] {scheduler_job.py:181} INFO - Started process (PID=177) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:14:45,534] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:14:45,535] {logging_mixin.py:104} INFO - [2023-12-05 16:14:45,535] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:14:45,562] {logging_mixin.py:104} INFO - [2023-12-05 16:14:45,558] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:14:45,564] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:14:45,585] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.059 seconds
[2023-12-05 16:15:15,717] {scheduler_job.py:181} INFO - Started process (PID=179) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:15:15,720] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:15:15,722] {logging_mixin.py:104} INFO - [2023-12-05 16:15:15,722] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:15:15,748] {logging_mixin.py:104} INFO - [2023-12-05 16:15:15,744] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:15:15,750] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:15:15,770] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.059 seconds
[2023-12-05 16:15:45,961] {scheduler_job.py:181} INFO - Started process (PID=181) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:15:45,973] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:15:45,975] {logging_mixin.py:104} INFO - [2023-12-05 16:15:45,975] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:15:45,995] {logging_mixin.py:104} INFO - [2023-12-05 16:15:45,991] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:15:45,996] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:15:46,014] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.062 seconds
[2023-12-05 16:16:16,141] {scheduler_job.py:181} INFO - Started process (PID=183) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:16:16,144] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:16:16,146] {logging_mixin.py:104} INFO - [2023-12-05 16:16:16,146] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:16:16,166] {logging_mixin.py:104} INFO - [2023-12-05 16:16:16,163] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:16:16,168] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:16:16,186] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.053 seconds
[2023-12-05 16:16:46,902] {scheduler_job.py:181} INFO - Started process (PID=185) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:16:46,907] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:16:46,910] {logging_mixin.py:104} INFO - [2023-12-05 16:16:46,910] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:16:46,938] {logging_mixin.py:104} INFO - [2023-12-05 16:16:46,934] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:16:46,940] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:16:46,958] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.065 seconds
[2023-12-05 16:17:17,696] {scheduler_job.py:181} INFO - Started process (PID=187) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:17:17,699] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:17:17,701] {logging_mixin.py:104} INFO - [2023-12-05 16:17:17,701] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:17:17,725] {logging_mixin.py:104} INFO - [2023-12-05 16:17:17,721] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:17:17,728] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:17:17,750] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.060 seconds
[2023-12-05 16:17:48,486] {scheduler_job.py:181} INFO - Started process (PID=189) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:17:48,489] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:17:48,491] {logging_mixin.py:104} INFO - [2023-12-05 16:17:48,491] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:17:48,513] {logging_mixin.py:104} INFO - [2023-12-05 16:17:48,509] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:17:48,514] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:17:48,533] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.053 seconds
[2023-12-05 16:18:19,251] {scheduler_job.py:181} INFO - Started process (PID=191) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:18:19,255] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:18:19,258] {logging_mixin.py:104} INFO - [2023-12-05 16:18:19,258] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:18:19,284] {logging_mixin.py:104} INFO - [2023-12-05 16:18:19,281] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:18:19,286] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:18:19,303] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 16:18:50,064] {scheduler_job.py:181} INFO - Started process (PID=193) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:18:50,068] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:18:50,070] {logging_mixin.py:104} INFO - [2023-12-05 16:18:50,070] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:18:50,092] {logging_mixin.py:104} INFO - [2023-12-05 16:18:50,089] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:18:50,094] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:18:50,111] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 16:19:20,743] {scheduler_job.py:181} INFO - Started process (PID=195) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:19:20,745] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:19:20,747] {logging_mixin.py:104} INFO - [2023-12-05 16:19:20,747] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:19:20,764] {logging_mixin.py:104} INFO - [2023-12-05 16:19:20,760] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:19:20,766] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:19:20,789] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.050 seconds
[2023-12-05 16:19:51,581] {scheduler_job.py:181} INFO - Started process (PID=197) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:19:51,585] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:19:51,588] {logging_mixin.py:104} INFO - [2023-12-05 16:19:51,588] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:19:51,613] {logging_mixin.py:104} INFO - [2023-12-05 16:19:51,609] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:19:51,615] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:19:51,633] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 16:20:22,330] {scheduler_job.py:181} INFO - Started process (PID=199) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:20:22,333] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:20:22,336] {logging_mixin.py:104} INFO - [2023-12-05 16:20:22,335] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:20:22,359] {logging_mixin.py:104} INFO - [2023-12-05 16:20:22,356] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:20:22,361] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:20:22,379] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 16:20:53,148] {scheduler_job.py:181} INFO - Started process (PID=201) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:20:53,152] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:20:53,154] {logging_mixin.py:104} INFO - [2023-12-05 16:20:53,154] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:20:53,178] {logging_mixin.py:104} INFO - [2023-12-05 16:20:53,174] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:20:53,179] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:20:53,196] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 16:21:23,864] {scheduler_job.py:181} INFO - Started process (PID=203) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:21:23,868] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:21:23,870] {logging_mixin.py:104} INFO - [2023-12-05 16:21:23,870] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:21:23,897] {logging_mixin.py:104} INFO - [2023-12-05 16:21:23,894] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:21:23,899] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:21:23,917] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 16:21:54,659] {scheduler_job.py:181} INFO - Started process (PID=205) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:21:54,664] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:21:54,666] {logging_mixin.py:104} INFO - [2023-12-05 16:21:54,666] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:21:54,690] {logging_mixin.py:104} INFO - [2023-12-05 16:21:54,686] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:21:54,692] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:21:54,711] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 16:22:25,448] {scheduler_job.py:181} INFO - Started process (PID=207) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:22:25,452] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:22:25,455] {logging_mixin.py:104} INFO - [2023-12-05 16:22:25,454] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:22:25,481] {logging_mixin.py:104} INFO - [2023-12-05 16:22:25,478] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:22:25,483] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:22:25,501] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.062 seconds
[2023-12-05 16:22:56,246] {scheduler_job.py:181} INFO - Started process (PID=209) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:22:56,250] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:22:56,252] {logging_mixin.py:104} INFO - [2023-12-05 16:22:56,252] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:22:56,275] {logging_mixin.py:104} INFO - [2023-12-05 16:22:56,271] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:22:56,277] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:22:56,294] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.055 seconds
[2023-12-05 16:23:27,024] {scheduler_job.py:181} INFO - Started process (PID=211) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:23:27,028] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:23:27,031] {logging_mixin.py:104} INFO - [2023-12-05 16:23:27,031] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:23:27,056] {logging_mixin.py:104} INFO - [2023-12-05 16:23:27,053] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:23:27,058] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:23:27,077] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.062 seconds
[2023-12-05 16:23:57,848] {scheduler_job.py:181} INFO - Started process (PID=213) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:23:57,853] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:23:57,856] {logging_mixin.py:104} INFO - [2023-12-05 16:23:57,855] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:23:57,882] {logging_mixin.py:104} INFO - [2023-12-05 16:23:57,878] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:23:57,884] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:23:57,901] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.063 seconds
[2023-12-05 16:24:28,656] {scheduler_job.py:181} INFO - Started process (PID=215) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:24:28,659] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:24:28,662] {logging_mixin.py:104} INFO - [2023-12-05 16:24:28,661] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:24:28,686] {logging_mixin.py:104} INFO - [2023-12-05 16:24:28,682] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:24:28,688] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:24:28,711] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.061 seconds
[2023-12-05 16:24:59,415] {scheduler_job.py:181} INFO - Started process (PID=217) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:24:59,419] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:24:59,421] {logging_mixin.py:104} INFO - [2023-12-05 16:24:59,421] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:24:59,444] {logging_mixin.py:104} INFO - [2023-12-05 16:24:59,440] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:24:59,445] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:24:59,463] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.056 seconds
[2023-12-05 16:25:30,243] {scheduler_job.py:181} INFO - Started process (PID=219) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:25:30,247] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:25:30,249] {logging_mixin.py:104} INFO - [2023-12-05 16:25:30,249] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:25:30,272] {logging_mixin.py:104} INFO - [2023-12-05 16:25:30,269] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:25:30,274] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:25:30,292] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.058 seconds
[2023-12-05 16:26:00,925] {scheduler_job.py:181} INFO - Started process (PID=221) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:26:00,929] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:26:00,932] {logging_mixin.py:104} INFO - [2023-12-05 16:26:00,931] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:26:00,959] {logging_mixin.py:104} INFO - [2023-12-05 16:26:00,954] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:26:00,961] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:26:00,983] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.065 seconds
[2023-12-05 16:26:31,748] {scheduler_job.py:181} INFO - Started process (PID=223) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:26:31,752] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:26:31,754] {logging_mixin.py:104} INFO - [2023-12-05 16:26:31,754] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:26:31,778] {logging_mixin.py:104} INFO - [2023-12-05 16:26:31,774] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:26:31,780] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:26:31,798] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.058 seconds
[2023-12-05 16:27:02,443] {scheduler_job.py:181} INFO - Started process (PID=225) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:27:02,447] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:27:02,450] {logging_mixin.py:104} INFO - [2023-12-05 16:27:02,449] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:27:02,475] {logging_mixin.py:104} INFO - [2023-12-05 16:27:02,471] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:27:02,476] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:27:02,498] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.063 seconds
[2023-12-05 16:27:32,941] {scheduler_job.py:181} INFO - Started process (PID=227) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:27:32,945] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:27:32,947] {logging_mixin.py:104} INFO - [2023-12-05 16:27:32,947] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:27:32,966] {logging_mixin.py:104} INFO - [2023-12-05 16:27:32,962] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:27:32,969] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:27:33,296] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.359 seconds
[2023-12-05 16:28:04,037] {scheduler_job.py:181} INFO - Started process (PID=229) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:28:04,041] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:28:04,042] {logging_mixin.py:104} INFO - [2023-12-05 16:28:04,042] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:28:04,063] {logging_mixin.py:104} INFO - [2023-12-05 16:28:04,059] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:28:04,065] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:28:04,369] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.341 seconds
[2023-12-05 16:28:34,859] {scheduler_job.py:181} INFO - Started process (PID=231) to work on /opt/airflow/dags/API_dag.py
[2023-12-05 16:28:34,862] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/API_dag.py for tasks to queue
[2023-12-05 16:28:34,864] {logging_mixin.py:104} INFO - [2023-12-05 16:28:34,863] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/API_dag.py
[2023-12-05 16:28:34,885] {logging_mixin.py:104} INFO - [2023-12-05 16:28:34,881] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/API_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/API_dag.py", line 7, in <module>
    from script_de_prediction import predict, preprocess_text, preprocess_image
ModuleNotFoundError: No module named 'script_de_prediction'
[2023-12-05 16:28:34,887] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/API_dag.py
[2023-12-05 16:28:35,097] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/API_dag.py took 0.242 seconds
